name: discord_music_bot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ffmpeg
  - nodejs
  - pip
  - pip:
    - discord.py[voice]
    - yt-dlp>=2025.01.26
    - python-dotenv
    - spotipy
    - requests
    - beautifulsoup4
    - setuptools
